import os
from typing import Dict

import geopandas as gpd
import keplergl
import osmnx as ox


def plot_geodataframes_on_kepler_map(gdfs: Dict[str, gpd.GeoDataFrame], height=750, kepler_config=None):
    if kepler_config in KEPLER_CONFIGS:
        kepler_config = KEPLER_CONFIGS[kepler_config]
    else:
        kepler_config = {}
    m = keplergl.KeplerGl(data=gdfs, height=height, config=kepler_config)
    return m


def plot_graph(g, filename, show=True, save=False, output_dir='', e_c='#999999'):
    if output_dir:
        filepath = os.path.join(output_dir, filename + '.png')
    else:
        filepath = None
    return ox.plot_graph(
        g, filepath=filepath, node_size=2, edge_color=e_c, save=save, show=show)


def plot_graph_routes(g, routes, filename, show=True, save=False, output_dir=''):
    if output_dir:
        filepath = os.path.join(output_dir, filename + '.png')
    else:
        filepath = None
    if len(routes) == 0:
        return ox.plot_graph(
            g, filepath=filepath, node_size=2, save=save, show=show)
    elif len(routes) == 1:
        return ox.plot_graph_route(
            g, route=routes[0], route_color="#F9A825", route_linewidth=1, orig_dest_size=5, node_size=2,
            filepath=filepath, save=save, show=show)
    else:
        return ox.plot_graph_routes(
            g, routes=routes, route_colors="#F9A825", route_linewidth=1, orig_dest_size=5, node_size=2,
            filepath=filepath, save=save, show=show)


def plot_non_routed_schedule_graph(g, filename, ax=None, show=True, save=False, output_dir=''):
    if output_dir:
        filepath = os.path.join(output_dir, filename + '.png')
    else:
        filepath = None
    return ox.plot_graph(
        g,
        ax=ax,
        filepath=filepath,
        node_size=1,
        edge_color='#F9A825',
        node_color='#F9A825',
        save=save,
        show=show)


KEPLER_CONFIGS = {
    'network_with_pt': {'version': 'v1',
                        'config': {'visState': {'filters': [],
                                                'layers': [{'id': 'network_links',
                                                            'type': 'geojson',
                                                            'config': {'dataId': 'network_links',
                                                                       'label': 'network_links',
                                                                       'color': [227, 227, 227],
                                                                       'highlightColor': [252, 242, 26, 255],
                                                                       'columns': {'geojson': 'geometry'},
                                                                       'isVisible': True,
                                                                       'visConfig': {'opacity': 0.8,
                                                                                     'strokeOpacity': 0.8,
                                                                                     'thickness': 0.5,
                                                                                     'strokeColor': None,
                                                                                     'colorRange': {
                                                                                         'name': 'Global Warming',
                                                                                         'type': 'sequential',
                                                                                         'category': 'Uber',
                                                                                         'colors': ['#5A1846',
                                                                                                    '#900C3F',
                                                                                                    '#C70039',
                                                                                                    '#E3611C',
                                                                                                    '#F1920E',
                                                                                                    '#FFC300']},
                                                                                     'strokeColorRange': {
                                                                                         'name': 'Global Warming',
                                                                                         'type': 'sequential',
                                                                                         'category': 'Uber',
                                                                                         'colors': ['#5A1846',
                                                                                                    '#900C3F',
                                                                                                    '#C70039',
                                                                                                    '#E3611C',
                                                                                                    '#F1920E',
                                                                                                    '#FFC300']},
                                                                                     'radius': 10,
                                                                                     'sizeRange': [0, 10],
                                                                                     'radiusRange': [0, 50],
                                                                                     'heightRange': [0, 500],
                                                                                     'elevationScale': 5,
                                                                                     'enableElevationZoomFactor': True,
                                                                                     'stroked': True,
                                                                                     'filled': False,
                                                                                     'enable3d': False,
                                                                                     'wireframe': False},
                                                                       'hidden': False,
                                                                       'textLabel': [{'field': None,
                                                                                      'color': [255, 255, 255],
                                                                                      'size': 18,
                                                                                      'offset': [0, 0],
                                                                                      'anchor': 'start',
                                                                                      'alignment': 'center'}]},
                                                            'visualChannels': {'colorField': None,
                                                                               'colorScale': 'quantize',
                                                                               'strokeColorField': None,
                                                                               'strokeColorScale': 'quantize',
                                                                               'sizeField': None,
                                                                               'sizeScale': 'linear',
                                                                               'heightField': None,
                                                                               'heightScale': 'linear',
                                                                               'radiusField': None,
                                                                               'radiusScale': 'linear'}},
                                                           {'id': 'schedule_routes',
                                                            'type': 'geojson',
                                                            'config': {'dataId': 'schedule_routes',
                                                                       'label': 'schedule_routes',
                                                                       'color': [30, 150, 190],
                                                                       'highlightColor': [252, 242, 26, 255],
                                                                       'columns': {'geojson': 'geometry'},
                                                                       'isVisible': True,
                                                                       'visConfig': {'opacity': 0.8,
                                                                                     'strokeOpacity': 0.49,
                                                                                     'thickness': 1.8,
                                                                                     'strokeColor': None,
                                                                                     'colorRange': {
                                                                                         'name': 'Global Warming',
                                                                                         'type': 'sequential',
                                                                                         'category': 'Uber',
                                                                                         'colors': ['#5A1846',
                                                                                                    '#900C3F',
                                                                                                    '#C70039',
                                                                                                    '#E3611C',
                                                                                                    '#F1920E',
                                                                                                    '#FFC300']},
                                                                                     'strokeColorRange': {
                                                                                         'name': 'Uber Viz Qualitative 4',
                                                                                         'type': 'qualitative',
                                                                                         'category': 'Uber',
                                                                                         'colors': ['#12939A',
                                                                                                    '#DDB27C',
                                                                                                    '#88572C',
                                                                                                    '#FF991F',
                                                                                                    '#F15C17',
                                                                                                    '#223F9A',
                                                                                                    '#DA70BF',
                                                                                                    '#125C77',
                                                                                                    '#4DC19C',
                                                                                                    '#776E57',
                                                                                                    '#17B8BE',
                                                                                                    '#F6D18A',
                                                                                                    '#B7885E',
                                                                                                    '#FFCB99',
                                                                                                    '#F89570',
                                                                                                    '#829AE3',
                                                                                                    '#E79FD5',
                                                                                                    '#1E96BE',
                                                                                                    '#89DAC1',
                                                                                                    '#B3AD9E']},
                                                                                     'radius': 10,
                                                                                     'sizeRange': [0, 10],
                                                                                     'radiusRange': [0, 50],
                                                                                     'heightRange': [0, 500],
                                                                                     'elevationScale': 5,
                                                                                     'enableElevationZoomFactor': True,
                                                                                     'stroked': True,
                                                                                     'filled': False,
                                                                                     'enable3d': False,
                                                                                     'wireframe': False},
                                                                       'hidden': False,
                                                                       'textLabel': [{'field': None,
                                                                                      'color': [255, 255, 255],
                                                                                      'size': 18,
                                                                                      'offset': [0, 0],
                                                                                      'anchor': 'start',
                                                                                      'alignment': 'center'}]},
                                                            'visualChannels': {'colorField': None,
                                                                               'colorScale': 'quantize',
                                                                               'strokeColorField': {'name': 'mode',
                                                                                                    'type': 'string'},
                                                                               'strokeColorScale': 'ordinal',
                                                                               'sizeField': None,
                                                                               'sizeScale': 'linear',
                                                                               'heightField': None,
                                                                               'heightScale': 'linear',
                                                                               'radiusField': None,
                                                                               'radiusScale': 'linear'}}],
                                                'interactionConfig': {
                                                    'tooltip': {'fieldsToShow': {'network_links': [{'name': 'id',
                                                                                                    'format': None},
                                                                                                   {'name': 'from',
                                                                                                    'format': None},
                                                                                                   {'name': 'to',
                                                                                                    'format': None},
                                                                                                   {'name': 'freespeed',
                                                                                                    'format': None},
                                                                                                   {'name': 'capacity',
                                                                                                    'format': None}],
                                                                                 'schedule_routes': [
                                                                                     {'name': 'route_id',
                                                                                      'format': None},
                                                                                     {'name': 'mode', 'format': None},
                                                                                     {'name': 'route_short_name',
                                                                                      'format': None},
                                                                                     {'name': 'service_id',
                                                                                      'format': None}]},
                                                                'compareMode': False,
                                                                'compareType': 'absolute',
                                                                'enabled': True},
                                                    'brush': {'size': 0.5, 'enabled': False},
                                                    'geocoder': {'enabled': False},
                                                    'coordinate': {'enabled': False}},
                                                'layerBlending': 'normal',
                                                'splitMaps': [],
                                                'animationConfig': {'currentTime': None, 'speed': 1}},
                                   'mapStyle': {'styleType': 'dark',
                                                'topLayerGroups': {},
                                                'visibleLayerGroups': {'label': False,
                                                                       'road': True,
                                                                       'border': False,
                                                                       'building': True,
                                                                       'water': True,
                                                                       'land': True,
                                                                       '3d building': False},
                                                'threeDBuildingColor': [9.665468314072013,
                                                                        17.18305478057247,
                                                                        31.1442867897876],
                                                'mapStyles': {}}}},
    'schedule': {'version': 'v1',
                 'config': {'visState': {'filters': [],
                                         'layers': [{'id': 'schedule_links',
                                                     'type': 'geojson',
                                                     'config': {'dataId': 'schedule_links',
                                                                'label': 'schedule_links',
                                                                'color': [249, 168, 37],
                                                                'highlightColor': [252, 242, 26, 255],
                                                                'columns': {'geojson': 'geometry'},
                                                                'isVisible': True,
                                                                'visConfig': {'opacity': 0.8,
                                                                              'strokeOpacity': 0.8,
                                                                              'thickness': 0.5,
                                                                              'strokeColor': None,
                                                                              'colorRange': {'name': 'Global Warming',
                                                                                             'type': 'sequential',
                                                                                             'category': 'Uber',
                                                                                             'colors': ['#5A1846',
                                                                                                        '#900C3F',
                                                                                                        '#C70039',
                                                                                                        '#E3611C',
                                                                                                        '#F1920E',
                                                                                                        '#FFC300']},
                                                                              'strokeColorRange': {
                                                                                  'name': 'Global Warming',
                                                                                  'type': 'sequential',
                                                                                  'category': 'Uber',
                                                                                  'colors': ['#5A1846',
                                                                                             '#900C3F',
                                                                                             '#C70039',
                                                                                             '#E3611C',
                                                                                             '#F1920E',
                                                                                             '#FFC300']},
                                                                              'radius': 10,
                                                                              'sizeRange': [0, 10],
                                                                              'radiusRange': [0, 50],
                                                                              'heightRange': [0, 500],
                                                                              'elevationScale': 5,
                                                                              'enableElevationZoomFactor': True,
                                                                              'stroked': True,
                                                                              'filled': False,
                                                                              'enable3d': False,
                                                                              'wireframe': False},
                                                                'hidden': False,
                                                                'textLabel': [{'field': None,
                                                                               'color': [255, 255, 255],
                                                                               'size': 18,
                                                                               'offset': [0, 0],
                                                                               'anchor': 'start',
                                                                               'alignment': 'center'}]},
                                                     'visualChannels': {'colorField': None,
                                                                        'colorScale': 'quantize',
                                                                        'strokeColorField': None,
                                                                        'strokeColorScale': 'quantize',
                                                                        'sizeField': None,
                                                                        'sizeScale': 'linear',
                                                                        'heightField': None,
                                                                        'heightScale': 'linear',
                                                                        'radiusField': None,
                                                                        'radiusScale': 'linear'}},
                                                    {'id': 'schedule_stops',
                                                     'type': 'point',
                                                     'config': {'dataId': 'schedule_stops',
                                                                'label': 'schedule_stops',
                                                                'color': [249, 95, 37],
                                                                'highlightColor': [252, 242, 26, 255],
                                                                'columns': {'lat': 'lat', 'lng': 'lon',
                                                                            'altitude': None},
                                                                'isVisible': True,
                                                                'visConfig': {'opacity': 0.8,
                                                                              'strokeOpacity': 0.8,
                                                                              'thickness': 0.5,
                                                                              'strokeColor': None,
                                                                              'colorRange': {'name': 'Global Warming',
                                                                                             'type': 'sequential',
                                                                                             'category': 'Uber',
                                                                                             'colors': ['#5A1846',
                                                                                                        '#900C3F',
                                                                                                        '#C70039',
                                                                                                        '#E3611C',
                                                                                                        '#F1920E',
                                                                                                        '#FFC300']},
                                                                              'strokeColorRange': {
                                                                                  'name': 'Global Warming',
                                                                                  'type': 'sequential',
                                                                                  'category': 'Uber',
                                                                                  'colors': ['#5A1846',
                                                                                             '#900C3F',
                                                                                             '#C70039',
                                                                                             '#E3611C',
                                                                                             '#F1920E',
                                                                                             '#FFC300']},
                                                                              'radius': 10,
                                                                              'sizeRange': [0, 10],
                                                                              'radiusRange': [0, 50],
                                                                              'heightRange': [0, 500],
                                                                              'elevationScale': 5,
                                                                              'enableElevationZoomFactor': True,
                                                                              'stroked': False,
                                                                              'filled': True,
                                                                              'enable3d': False,
                                                                              'wireframe': False},
                                                                'hidden': False,
                                                                'textLabel': [
                                                                    {'field': {'name': 'name', 'type': 'string'},
                                                                     'color': [255, 255, 255],
                                                                     'size': 11,
                                                                     'offset': [0, 0],
                                                                     'anchor': 'start',
                                                                     'alignment': 'center'}]},
                                                     'visualChannels': {'colorField': None,
                                                                        'colorScale': 'quantize',
                                                                        'strokeColorField': None,
                                                                        'strokeColorScale': 'quantize',
                                                                        'sizeField': None,
                                                                        'sizeScale': 'linear',
                                                                        'heightField': None,
                                                                        'heightScale': 'linear',
                                                                        'radiusField': None,
                                                                        'radiusScale': 'linear'}}],
                                         'interactionConfig': {
                                             'tooltip': {'fieldsToShow': {'links': [{'name': 'services',
                                                                                     'format': None},
                                                                                    {'name': 'routes', 'format': None},
                                                                                    {'name': 'u', 'format': None},
                                                                                    {'name': 'v', 'format': None}],
                                                                          'stops': [
                                                                              {'name': 'services', 'format': None},
                                                                              {'name': 'routes', 'format': None},
                                                                              {'name': 'id', 'format': None},
                                                                              {'name': 'x', 'format': None},
                                                                              {'name': 'y', 'format': None}]},
                                                         'compareMode': False,
                                                         'compareType': 'absolute',
                                                         'enabled': True},
                                             'brush': {'size': 0.5, 'enabled': False},
                                             'geocoder': {'enabled': False},
                                             'coordinate': {'enabled': False}},
                                         'layerBlending': 'normal',
                                         'splitMaps': [],
                                         'animationConfig': {'currentTime': None, 'speed': 1}},
                            'mapState': {'bearing': 0,
                                         'dragRotate': False,
                                         'latitude': 51.52009753324012,
                                         'longitude': -0.13881798709273885,
                                         'pitch': 0,
                                         'zoom': 14,
                                         'isSplit': False},
                            'mapStyle': {'styleType': 'dark',
                                         'topLayerGroups': {},
                                         'visibleLayerGroups': {'label': False,
                                                                'road': True,
                                                                'border': False,
                                                                'building': True,
                                                                'water': True,
                                                                'land': True,
                                                                '3d building': False},
                                         'threeDBuildingColor': [9.665468314072013,
                                                                 17.18305478057247,
                                                                 31.1442867897876],
                                         'mapStyles': {}}}}
}
from copy import deepcopy
KEPLER_CONFIGS['network_and_schedule'] = deepcopy(KEPLER_CONFIGS['network_with_pt'])
KEPLER_CONFIGS['network_and_schedule']['config']['visState']['layers'] += KEPLER_CONFIGS['schedule']['config']['visState']['layers']

print('')
