OSM_TAGS:
  # tags that are included when reading OSM data, this is the minimal suggested set
  USEFUL_TAGS_NODE:
    - ref
    - highway
  USEFUL_TAGS_PATH:
    - bridge
    - tunnel
    - oneway
    - lanes
    - highway
    - service
    - access
    - railway
    - route
    - lanes
    - oneway
    - psv
    - vehicle
    - junction
    - osmid

MODES:
  MODE_INDICATORS:
    # These refer to tags stored in OSM, the mode assignment to tags is manual and definitely not exhaustive.
    # If a tag is not listed here, it will not be read into the network. This is where you should define how dense
    # you want your network to be.
    highway:
      motorway:
        - car
      motorway_link:
        - car
      trunk:
        - car
      trunk_link:
        - car
      primary:
        - car
        - walk
        - bike
      primary_link:
        - car
        - walk
        - bike
      secondary:
        - car
        - walk
        - bike
      secondary_link:
        - car
        - walk
        - bike
      tertiary:
        - car
        - walk
        - bike
      tertiary_link:
        - car
        - walk
        - bike
      unclassified:
        - car
        - walk
        - bike
    railway:
      - rail

  DEFAULT_OSM_TAG_VALUE:
  # GeNet will first look at OSM tags to infer the matsim values the link should have. For the types and values head over to
  # output/matsim_xml_values.py.
    car: secondary
    bus: secondary
    rail: railway
    subway: railway
    bike: living_street
    walk: pedestrian
