name: Daily CI

on:
  schedule:
    - cron: '37 14 * * 1-5'  # checks on the 37th minute of the 14th hour every weekday

jobs:
  get-date:
    runs-on: ubuntu-latest
    steps:
      - name: Add date to github output env
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  test:
    needs: get-date
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-install-lint-test.yml@v1.1.0
    with:
      os: ubuntu-latest
      py3version: "12"
      notebook_kernel: genet
      pytest_args: '--no-cov'  # ignore coverage
      cache_env: false
      lint: false
      env_name: daily-ci
      additional_env_create_args: coin-or-cbc

  slack-notify-ci:
    needs: test
    if: always()
    uses: arup-group/actions-city-modelling-lab/.github/workflows/slack-notify.yml@v1.1.0
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    with:
      result: needs.test.result
      channel: genet-feed
      message: Daily CI action
